<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Shopreviews\Connect\Block\Widget\Review\Badge;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var Badge $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var HeroiconsSolid $heroicons */

$heroicons = $viewModels->require(HeroiconsSolid::class);

$uniqId= $block->getUniqueId();
$website = $block->getWebsite();
$fm = $block->formatter();

$shopreviewsLogo = $block->getViewFileUrl('Shopreviews_Connect::images/shopreviews-logo.png');

if(!$website) { return; }

$reviewCount = $website->getReviewCount();
$reviewLabel = $reviewCount > 1 ? __('reviews') : __('review');
$sourcesCount = $website->getSourceCount();
?>

<script>
    'use strict';

    document.addEventListener('alpine:init', () => {
        Alpine.store('shopreviews_<?= $uniqId ?>', {
            additionalClass: "<?= /* @noEscape */ $block->getSectionClass(); ?>",
            modalType: "<?= /* @noEscape */ $block->getModalType(); ?>",
            showModal: false,
            activePlatform: 'all',
            loaded: false,
            init() {
                this.loaded = true;
            },
            setPlatform(platform) {
                this.activePlatform = platform === this.activePlatform ? 'all' : platform;
            }
        });
    });
</script>

<section x-data="{ store: Alpine.store('shopreviews_<?= $uniqId ?>') }" 
         class="group relative inline-block py-2 pr-5 pl-12 rounded-3xl bg-[#fb3b38] text-white text-base"
         :class="{
            'cursor-pointer': store.additionalClass.includes('modal-enabled'),
            '!fixed z-50': !store.additionalClass.includes('manual'),
            'top-3 right-3': store.additionalClass.includes('top_right'),
            'top-3 left-3': store.additionalClass.includes('top_left'),
            'bottom-3 right-3': store.additionalClass.includes('bottom_right'),
            'bottom-3 left-3': store.additionalClass.includes('bottom_left'),
            'bottom-10 right-0 origin-bottom-right rounded-b-none': store.additionalClass.includes('sticky_on_right'),
            'bottom-10 left-0 origin-bottom-left rounded-t-none': store.additionalClass.includes('sticky_on_left'),
            '!p-0': ['manual', 'top_right', 'top_left', 'bottom_right', 'bottom_left'].some(cls => store.additionalClass.includes(cls)) && store.additionalClass.includes('slide_down')
         }"
        :style="store.additionalClass.includes('sticky_on_right') ? 'transform: rotate(-90deg) translateX(100%);' : 
                store.additionalClass.includes('sticky_on_left') ? 'transform: rotate(-90deg) translateY(100%);' : ''"
        x-on:click="store.showModal = true"
>
    
    <span x-cloak x-show="store.additionalClass.includes('sticky_on_right')"
          class="absolute bottom-0 -left-7 border-l-[36px] border-l-transparent border-r-0 border-r-transparent border-b-[24px] border-b-[#fb3b38]"></span>

    <span x-cloak x-show="store.additionalClass.includes('sticky_on_left')"
          class="absolute top-0 -left-7 border-l-[36px] border-l-transparent border-r-0 border-r-transparent border-t-[24px] border-t-[#fb3b38]"></span>

    <span :class="{
        'relative z-10 inline-block py-2 pr-4 pl-11 rounded-3xl bg-[#fb3b38]': ['manual', 'top_right', 'top_left', 'bottom_right', 'bottom_left'].some(cls => store.additionalClass.includes(cls)) && store.additionalClass.includes('slide_down')
    }">
        <span class="absolute top-2 left-3"
              :class="{ 'rotate-[19deg]': store.additionalClass.includes('sticky_on_right') || store.additionalClass.includes('sticky_on_left') }">
            <?= $heroicons->starHtml('', 24, 24); ?>
        </span>
        <b><?= $escaper->escapeHtml($website->getAvgRating()); ?></b>
    </span>

    <span :class="{ 
        'hidden': store.additionalClass.includes('never'),
        'absolute inset-0 -z-10 flex justify-center bg-white rounded-[20px] border border-[#e5e7eb] text-[#1e204f] text-xs text-center transition-all duration-300 [&>span]:hidden': ['manual', 'top_right', 'top_left', 'bottom_right', 'bottom_left'].some(cls => store.additionalClass.includes(cls)) && store.additionalClass.includes('slide_down'),
        'items-end pt-1 px-1.5 pb-2 group-hover:-top-1 group-hover:-right-1.5 group-hover:-left-1.5 group-hover:-bottom-8 [&_b]:font-normal': ['manual', 'top_right', 'top_left'].some(cls => store.additionalClass.includes(cls)) && store.additionalClass.includes('slide_down'),
        'items-start pt-2 px-1.5 pb-1 group-hover:-top-8 group-hover:-right-1.5 group-hover:-left-1.5 group-hover:-bottom-1.5 [&_b]:font-normal': ['bottom_right', 'bottom_left'].some(cls => store.additionalClass.includes(cls)) && store.additionalClass.includes('slide_down'),
        'group-hover:max-w-[200px] inline-flex gap-1 max-w-0 overflow-hidden whitespace-nowrap transition-all duration-300': ['manual', 'top_right', 'top_left', 'bottom_right', 'bottom_left'].some(cls => store.additionalClass.includes(cls)) && store.additionalClass.includes('slide_right')
    }">
        <?= $escaper->escapeHtml(__(
            '<span>based on</span> <b>%1 %2</b>', $reviewCount, $reviewLabel
        ), ['span', 'b']); ?>
    </span>
</section>

<?php if ($block->enableModalLink()): ?>
    <div x-data="{ store: Alpine.store('shopreviews_<?= $uniqId ?>') }"
        class="fixed z-50 w-[90%]"
        style="display: none;"
        :class="{
            '!block': store.loaded,
            'top-1/2 left-1/2 max-w-2xl max-h-[90vh] opacity-0 invisible transition-opacity duration-300': store.modalType === 'popup',
            'top-0 right-0 max-w-lg h-screen transition-transform duration-500': store.modalType === 'slideout',
            '!visible !opacity-100': store.modalType === 'popup' && store.showModal,
            '!translate-x-0': store.modalType === 'slideout' && store.showModal
        }"
        :style="store.modalType === 'popup' ? 'transform: translate(-50%, -50%);' : 
                store.modalType === 'slideout' ? 'transform: translateX(105%)' : ''"
    >
        
        <div class="flex flex-col bg-white border border-[#e5e7eb]"
            :class="{
                'max-h-[90vh] rounded-xl': store.modalType === 'popup',
                'max-h-screen h-full': store.modalType === 'slideout'
            }"
        >
            <div class="relative text-center py-8 px-5 border-b border-[#e5e7eb]">
                <div data-element="shopreviews-logo" class="mb-6">
                    <img src="<?= $escaper->escapeUrl($shopreviewsLogo) ?>" class="absolute top-3 left-4" alt="Shopreview logo" width="158" height="29"/>
                </div>

                <h2 class="text-3xl font-semibold mb-2 [&_span]:text-xl [&_span]:font-light">
                    <?= $escaper->escapeHtml(__(
                        '%1 <span>/ %2</span>', $website->getAvgRating(), $block->getMaxRating()
                    ), ['span']); ?>
                </h2>
                
                <?= $block->getLayout()
                    ->createBlock(Shopreviews\Connect\Block\Widget\Helper\Stars::class)
                    ->setTemplate('Shopreviews_HyvaConnect::widget/helper/stars.phtml')
                    ->setData('svgSize', '40')
                    ->setData('percent', $website->getAvgRating() / $block->getMaxRating() * 100)
                    ->toHtml();
                ?>

                <div class="text-[15px] tracking-wider mt-3">
                    <?php if ($sourcesCount): ?>
                        <?= $escaper->escapeHtml(__(
                            'Based on <b>%1 %2</b> from <b>%3 sources</b>', $reviewCount, $reviewLabel, $sourcesCount
                        ), ['b']); ?>
                    <?php else: ?>
                        <?= $escaper->escapeHtml(__(
                            'Based on <b>%1 %2</b>', $reviewCount, $reviewLabel,
                        ), ['b']); ?>
                    <?php endif; ?>
                </div>

                <span class="absolute top-4 right-4 flex items-center justify-center w-8 h-8 opacity-50 rounded-full 
                           bg-[#d4cacc] text-white transition-all duration-300 hover:opacity-90 cursor-pointer"
                        x-on:click="store.showModal = false">
                    <?= $heroicons->xHtml('', 24, 24); ?>
                </span>
            </div>

            <?php if ($website->getSourceCount() > 1): ?>
                <div class="hidden sm:grid border-b border-[#e5e7eb] grid-cols-3">
                    <?php /** @var \Shopreviews\Connect\Api\Source\DataInterface $source */ ?>
                    <?php $index = 1; ?>
                    <?php foreach ($block->getSources() as $source): ?>
                        <div class="h-24 p-7 border-r border-[#e5e7eb] transition-colors duration-300 cursor-pointer
                                    hover:bg-[#f9f9f9]"
                             :class="{ 'bg-[#f9f9f9]': store.activePlatform === '<?= $escaper->escapeHtml($source->getPlatformName()); ?>' }"
                             x-on:click="store.setPlatform('<?= $escaper->escapeHtml($source->getPlatformName()); ?>')" 
                             style="<?= $index % 3 === 0 ? 'border-right: none;' : '' ?>">
                            <img src="<?= $escaper->escapeUrl($block->getMediaImageUrl($source->getPlatformLogo())) ?>"
                                 alt="<?= $escaper->escapeHtml($source->getPlatformName()); ?>"
                                 class="w-full h-full object-contain" />
                        </div>
                        <?php $index +=1 ; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <div class="h-full overflow-auto" style="max-height: calc(100% - 10px);">
                <?php /** @var \Shopreviews\Connect\Api\Review\DataInterface $review */ ?>
                <?php foreach ($block->getReviews() as $review): ?>
                    <div class="px-5 py-7 border-b border-[#e5e7eb] last:border-b-0"
                         :class="{ 
                            'block': store.activePlatform === 'all' || store.activePlatform === '<?= $escaper->escapeHtml($review->getPlatformName()); ?>',
                            'hidden': store.activePlatform !== 'all' && store.activePlatform !== '<?= $escaper->escapeHtml($review->getPlatformName()); ?>',
                        }">
                        
                        <div class="flex items-center justify-between flex-wrap gap-5 mb-5 [&_[data-element=box-stars]]:-ml-1">
                            <?= $block->getLayout()
                                ->createBlock(Shopreviews\Connect\Block\Widget\Helper\Stars::class)
                                ->setTemplate('Shopreviews_HyvaConnect::widget/helper/stars.phtml')
                                ->setData('svgSize', '24')
                                ->setData('percent', $review->getRating() / $block->getMaxRating() * 100)
                                ->toHtml();
                            ?>
                            <span class="flex items-center gap-2.5 opacity-50">
                                <?= $heroicons->userHtml('relative -top-0.5', 18, 18); ?>
                                <span>
                                    <?= $escaper->escapeHtml($review->getName()) ?>
                                </span>
                            </span>
                        </div>

                        <div class="mb-7 text-[15px] leading-7">
                            <?= $escaper->escapeHtml($review->getDescription()) ?>
                        </div>

                        <div class="flex items-center justify-between flex-wrap gap-5 text-sm">
                            <span class="flex items-center gap-1.5 [&_i]:font-normal [&_i]: opacity-70">
                                <span class="inline-flex items-center justify-center w-8 h-8 mr-1.5 p-2
                                            rounded-full border border-[#e5e7eb] shadow box-border">
                                    <?php $icon = $block->getMediaImageUrl($review->getPlatformIcon()); ?>
                                    <img src="<?= $escaper->escapeUrl($icon); ?>"
                                        alt="<?= $escaper->escapeHtml($review->getPlatformName()); ?>"
                                        width="20" height="20"
                                        class="w-full h-full object-contain" />
                                </span>
                                <?= $escaper->escapeHtml(__(
                                    '<b>From:</b> <i>%1</i>',
                                    $review->getPlatformName()
                                ), ['b', 'i']); ?>
                            </span>
                            <span class="opacity-70">
                                <?= $escaper->escapeHtml($fm->date($review->getReviewDate())); ?>
                            </span>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <span   x-data="{ store: Alpine.store('shopreviews_<?= $uniqId ?>') }"
            class="fixed inset-0 z-40 opacity-0 invisible bg-black/40 transition-opacity duration-300"
            :class="{ '!visible !opacity-100': store.showModal }"
            x-on:click="store.showModal = false"></span>
<?php endif; ?>
